version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test --coverage
            - run: bash <(curl -s https://codecov.io/bash)
            - run: yarn format:check
            - run: yarn lint
            - run: yarn build
workflows:
  build-and-test:
    jobs:
      - build-and-test
